### ISSUE TITLE
Add Marker Numbers  

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/NavigatorMaps#6]
Add Marker Numbers as visible in the mockup
http://informationcart.com/Maps/GoogleMap.html

- Left of Photo on List
- Markers on Map 

![markers](https://cloud.githubusercontent.com/assets/887805/8664196/e1b87480-29a1-11e5-8f98-b9a150bcbf05.png)

**Comment by xibbit** [comment]
Marker Numbers added

**Comment by stuartshay** [comment]
-- Selected Marker Moves when Dragging the Map Center Point 
-- Selected Point Should be Yellow
-- On the Map Marker can be Clicked and the Selected Point will turn Red and selected in the List

The Mockup has this Functionality 

![selectedmap](https://cloud.githubusercontent.com/assets/887805/8715482/8fd6966e-2b50-11e5-9215-9e26e55ea529.png)

**Comment by xibbit** [comment]
Pushed to map branch. Can we use previous markers instead of this with labels around the corners.
Numbered markers are coming from http://gmaps-samples.googlecode.com/svn/trunk/markers/
Yellow markers are not available. There are only 100 images per color for numbered markers.
Please review the same.

**Comment by stuartshay** [comment]
The Markers are fine for now just need the Red and blue

Latter on if there are more the 100 markers we can do something different
